import { Component, OnInit } from '@angular/core';
import { DisplayCar } from 'src/app/models/display-car';

@Component({
  selector: 'app-cars',
  templateUrl: './cars.component.html',
  styleUrls: ['./cars.component.css'],
})
export class CarsComponent implements OnInit {
  public cars: DisplayCar[] = [
    {
      img: '/assets/slideShow/PIKI.JPG',
      year: 2021,
      company: 'KIA',
      model: 'PIKANTO',
      gearBox: 'Auto',
      bookedDates: [],
      price: 150,
    },
    {
      img: 'assets/slideShow/i30.JPG',
      year: 2022,
      company: 'HYUNDAI',
      model: 'I30',
      gearBox: 'Auto',
      bookedDates: [],
      price: 300,
    },
    {
      img: '/assets/slideShow/PIKI.JPG',
      year: 2021,
      company: 'KIA',
      model: 'PIKANTO',
      gearBox: 'Auto',
      bookedDates: [],
      price: 150,
    },
    {
      img: 'assets/slideShow/i30.JPG',
      year: 2022,
      company: 'HYUNDAI',
      model: 'I30',
      gearBox: 'Manual',
      bookedDates: [],
      price: 300,
    },
    {
      img: '/assets/slideShow/PIKI.JPG',
      year: 2021,
      company: 'KIA',
      model: 'PIKANTO',
      gearBox: 'Auto',
      bookedDates: [],
      price: 150,
    },
    {
      img: 'assets/slideShow/i30.JPG',
      year: 2022,
      company: 'HYUNDAI',
      model: 'I30',
      gearBox: 'Auto',
      bookedDates: [],
      price: 300,
    },
    {
      img: '/assets/slideShow/PIKI.JPG',
      year: 2021,
      company: 'KIA',
      model: 'PIKANTO',
      gearBox: 'Auto',
      bookedDates: [],
      price: 150,
    },
    {
      img: 'assets/slideShow/i30.JPG',
      year: 2022,
      company: 'HYUNDAI',
      model: 'I30',
      gearBox: 'Auto',
      bookedDates: [],
      price: 300,
    },
    {
      img: '/assets/slideShow/PIKI.JPG',
      year: 2021,
      company: 'KIA',
      model: 'PIKANTO',
      gearBox: 'Auto',
      bookedDates: [],
      price: 150,
    },
    {
      img: 'assets/slideShow/i30.JPG',
      year: 2022,
      company: 'HYUNDAI',
      model: 'I30',
      gearBox: 'Auto',
      bookedDates: [],
      price: 300,
    },
    {
      img: '/assets/slideShow/PIKI.JPG',
      year: 2021,
      company: 'KIA',
      model: 'PIKANTO',
      gearBox: 'Auto',
      bookedDates: [],
      price: 150,
    },
    {
      img: 'assets/slideShow/i30.JPG',
      year: 2022,
      company: 'HYUNDAI',
      model: 'I30',
      gearBox: 'Auto',
      bookedDates: [],
      price: 300,
    },
    {
      img: '/assets/slideShow/PIKI.JPG',
      year: 2021,
      company: 'KIA',
      model: 'PIKANTO',
      gearBox: 'Auto',
      bookedDates: [],
      price: 150,
    },
    {
      img: 'assets/slideShow/i30.JPG',
      year: 2022,
      company: 'HYUNDAI',
      model: 'I30',
      gearBox: 'Auto',
      bookedDates: [],
      price: 300,
    },
    {
      img: '/assets/slideShow/PIKI.JPG',
      year: 2021,
      company: 'KIA',
      model: 'PIKANTO',
      gearBox: 'Auto',
      bookedDates: [],
      price: 150,
    },
    {
      img: 'assets/slideShow/i30.JPG',
      year: 2022,
      company: 'HYUNDAI',
      model: 'I30',
      gearBox: 'Auto',
      bookedDates: [],
      price: 300,
    },
  ];
  constructor() {}

  ngOnInit(): void {}
}
